# Generated by Django 4.1.4 on 2023-02-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('roll', models.IntegerField()),
                ('course', models.CharField(max_length=10)),
            ],
        ),
    ]
